sudo: false
language: python
env:
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="Django>=1.10,<1.11"
  - DJANGO_VERSION="Django>=1.11,<2.0"
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
python:
  # None of the currently supported Django versions support Python 2.6
  # - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# matrix:
#   exclude:
#     # Django 2.0 won't support Python 2.x anymore
#     - python: "2.7"
#       env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install coverage coveralls flake8 python-gnupg
  - pip install -q "$DJANGO_VERSION"
before_script:
  # Make sure we have gpg installed; this also logs the version of GPG
  - gpg --version
script:
  - flake8 email_extras --exclude=email_extras/migrations
  - coverage run --include=email_extras/*.py manage.py migrate
  - coverage run --include=email_extras/*.py --omit=email_extras/migrations/*.py manage.py test tests
after_script:
  - coverage combine
  - coveralls
matrix:
  allow_failures:
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
