# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='addresses',
            field=models.TextField(default=''),
        ),
    ]
