# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_extras', '0003_auto_20161103_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
